<?php
$mediaUrl = $this->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . "sm/tmp/image/";
$productImageUrl = $this->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . "catalog/product/";
$blog = $block->loadDetailBlog();
$productCollection = $block->loadProducts();
?>
<style>
    body, h1, h2, h3, h4, h5 {
        font-family: "Raleway", sans-serif
    }
</style>
<body class="w3-light-grey">

<!-- w3-content defines a container for fixed size centered content,
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">

    <!-- Header -->
    <header class="w3-container w3-center w3-padding-32">
        <h1><b>SMART BLOG</b></h1>
        <p>Welcome to the blog of <span class="w3-tag">Thuongnm2</span></p>
    </header>

    <!-- Grid -->
    <div class="w3-row">
        <!-- Blog entries -->
        <div class="w3-col l8 s12">
            <!-- Blog entry -->
            <div class="w3-card-4 w3-margin w3-white">
                <img src="<?= $mediaUrl . $blog['gallery'] ?>" alt="Nature" style="width: 100%">
                <div class="w3-container">
                    <h3><b><?= $blog['name'] ?></b></h3>
                    <h5><span class="w3-opacity"><?= $blog['publish_date_from'] ?></span></h5>
                </div>

                <div class="w3-container">
                    <p><?= $blog['description'] ?></p>
                </div>
            </div>
            <hr>
            <div class="hbr-main pad-main">
                <div class="block-title-main">
                    <h2>Related Products </h2>
                    <div class="title-border"></div>
                </div>
                <div class="hbr-main">
                    <div style="margin: 0 -10px;">
                        <div class="hbr-content hbr-slider">
                            <?php foreach ($productCollection as $product): ?>
                                <div class="hbr-inner">
                                    <table>
                                        <tr>
                                            <td height="300px"><img src="<?= $productImageUrl . $product->getImage() ?>" alt="Nature"
                                                     style="width: 100%"></td>
                                        </tr>
                                        <tr>
                                            <td><b><a href="#"><?= $product->getName() ?></a></b></td>
                                        </tr>
                                        <tr>
                                            <td> <?= $product->getPrice() ?> $</td>
                                        </tr>

                                    </table>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <script type="text/javascript" xml="space">// <![CDATA[
                        require(['jquery', 'cpowlcarousel'], function ($) {
                            jQuery(document).ready(function () {
                                jQuery(".hbr-slider").owlCarousel({
                                    items: 3,
                                    itemsDesktop: [1080, 4],
                                    itemsDesktopSmall: [860, 3],
                                    itemsTablet: [768, 3],
                                    itemsTabletSmall: [639, 3],
                                    itemsMobile: [479, 2],
                                    pagination: false,
                                    navigationText: ['<div class="lft-btn"><i class="fa fa-angle-left"></i></div>', '<div class="rgt-btn"><i class="fa fa-angle-right"></div>'],
                                    navigation: true,
                                });
                            });
                        });
                        // ]]></script>
                </div>
            </div>
            <!-- END BLOG ENTRIES -->
        </div>

        <!-- Introduction menu -->
        <div class="w3-col l4">
            <!-- Posts -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>Categories</h4>
                </div>
                <ul class="w3-ul w3-hoverable w3-white">
                    <?php foreach ($block->loadCategories() as $value): ?>
                        <li class="w3-padding-16">
                            <span class="w3-large"><?= $value['name'] ?></span><br>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <hr>

            <!-- Labels / tags -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding">
                    <h4>Tags</h4>
                </div>
                <div class="w3-container w3-white">
                    <p>
                        <?php foreach ($block->loadTags() as $value): ?>
                            <a href="#"><span
                                        class="w3-tag w3-light-grey w3-small w3-margin-bottom"><?= $value['name'] ?></span></a>
                        <?php endforeach; ?>
                    </p>
                </div>
            </div>
            <!-- END Introduction Menu -->
        </div>

        <!-- END GRID -->
    </div>
    <br>

    <!-- END w3-content -->
</div>


</body>
